by_metric:
  users_active_daily: [[app_version], [vertical, logical_category, region]]
  daily_active_users: [[app_version]]
  open_app: [[app_version]]
  buyers_canonical: [[price_group], [category, subcategory, param1], [vertical, logical_category, logical_param1, logical_param2, region]]
  contacts_canonical: 
    - [category, subcategory, param1]
    - [vertical, logical_category, logical_param1, logical_param2, region]
    - [vertical, logical_category, region, city, is_asd, user_segment_market]
  active_items:
  - [category, subcategory, param1, param2, is_asd, condition]
  - [vertical, logical_category, region, city, is_asd, condition]
  - [is_logged_in, vertical, logical_category, logical_param1, logical_param2, is_asd, condition, region]
  items_started_net: [[category, subcategory, param1, param2, is_asd, condition], [vertical, logical_category, region, city, condition, is_asd]]
  users_active_items: 
    - [category, subcategory, param1, is_asd]
    - [vertical, logical_category,logical_param1, region, condition, is_asd]
  users_item_started: [[category, subcategory, param1], [vertical, logical_category, region, condition]]
  sellers_with_contacts:
  - [category, subcategory, param1]
  - [vertical, logical_category, region]
  - [is_logged_in, vertical, logical_category, logical_param1, logical_param2, region]
  classified_amount_net_adj: 
    - [vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]
    - [vertical, logical_category, region, city, is_asd, user_segment_market]
  classified_transactions: [[vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]]
  classified_price_net_adj: [[vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]]
  classified_users: [[vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]]
  classified_transactions_per_user: [[vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]]
  classified_arppu_net_adj: [[vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]]
  cpa_amount_net_adj: [[vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]]
  cpa_transactions: [[vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]]
  extensions_amount_net_adj: [[vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]]
  extensions_transactions: [[vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]]
  lf_transactions: 
    - [vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]
    - [vertical, logical_category, region, city, is_asd, user_segment_market]
  lf_users: 
    - [vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]
    - [vertical, logical_category, region, city, is_asd, user_segment_market]
  vas_amount_net_adj: 
    - [vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]
    - [vertical, logical_category, region, city, is_asd, user_segment_market]
  vas_transactions: 
    - [vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]
    - [vertical, logical_category, region, city, is_asd, user_segment_market]
  vas_users: 
    - [vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]
    - [vertical, logical_category, region, city, is_asd, user_segment_market]
  vas_price_net_adj: [[vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]]
  vas_transactions_per_user: [[vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]]
  vas_arppu_net_adj: [[vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]]
  paid_contact_amount_net_adj: [[vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]]
  subs_amount_net_adj: [[vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]]
  subs_transactions: [[vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]]
  subs_w_extensions_amount_net_adj: 
    - [vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]
    - [vertical, logical_category, region, city, is_asd, user_segment_market]
  subs_w_extensions_transactions: 
    - [vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]
    - [vertical, logical_category, region, city, is_asd, user_segment_market]
  subs_w_extensions_price_net_adj: [[vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]]
  subs_w_extensions_users: 
    - [vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]
    - [vertical, logical_category, region, city, is_asd, user_segment_market]
  subs_w_extensions_transactions_per_user: [[vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]]
  subs_w_extensions_arppu_net_adj: [[vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]]
  lf_amount_net_adj: 
    - [vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]
    - [vertical, logical_category, region, city, is_asd, user_segment_market]
  lf_price_net_adj: [[vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]]
  lf_transactions_per_user: [[vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]]
  lf_arppu_net_adj: [[vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]]
  lf_amount_net:
    - [is_logged_in, is_asd, vertical, logical_category, logical_param1, logical_param2, region, user_segment_market]
  items_reactivated_net:
    - [is_logged_in, is_asd, vertical, logical_category, logical_param1, logical_param2, region, city, user_segment_market, condition]
  items_sold_onavito:
    - [is_logged_in, is_asd, vertical, logical_category, logical_param1, logical_param2, region, user_segment_market, condition]
  items_sold_onavito_per_items_reactivated_net:
    - [is_logged_in, is_asd, vertical, logical_category, logical_param1, logical_param2, region, user_segment_market]
  returned_buyers:
    - [is_logged_in, is_asd, vertical, logical_category, logical_param1, logical_param2, region, user_segment_market, condition]
    - [category, subcategory, param1, is_asd, condition]
  cnt_returned_buyers:
    - [is_logged_in, is_asd, vertical, logical_category, logical_param1, logical_param2, region, user_segment_market, condition]
    - [category, subcategory, param1, is_asd, condition]
  item_views: [[is_logged_in, vertical, logical_category, logical_param1, region, city, is_asd, condition], [vertical, logical_category, logical_param1, logical_param2, is_asd, condition]]
  contacts: [[is_logged_in, vertical, logical_category, region, city, is_asd, condition], [vertical, logical_category, logical_param1, logical_param2, is_asd, condition]]
  vas_amount_net: [[vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]]
  vas_amount_net_x2_7: [[vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]]
  vas_amount_net_x5_1: [[vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]]
  vas_amount_net_x2_1: [[vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]]
  vas_amount_net_x10_1: [[vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]]
  vas_amount_net_x10_7: [[vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]]
  vas_amount_net_x5_7: [[vertical, logical_category, logical_param1, logical_param2, region, city, is_asd, user_segment_market]]
  buyer_delivery_gmv_accepted:
    - [vertical, logical_category, logical_param1, logical_param2, user_segment_market]
  tariff_base_revenue: [[is_logged_in, vertical, logical_category, logical_param1, logical_param2, region]]
  tariff_pro_revenue: [[is_logged_in, vertical, logical_category, logical_param1, logical_param2, region]]
  active_listers: [[is_logged_in, vertical, logical_category, logical_param1, logical_param2, region, is_asd]]
  seller_contacts: [[is_logged_in, vertical, logical_category, logical_param1, logical_param2, region]]
  tickets_created_big10: [[logical_category, vertical, region, city, user_segment_market, is_asd]]
  users_with_created_tickets: [[logical_category, vertical, region, city, user_segment_market, is_asd]]
  revenue_total: [[category, subcategory]]
  revenue_net_total: [[category, subcategory]]
  revenue_net_adj_total: [[category, subcategory]]
  buyers_any:
    - [vertical, logical_category, region, city, is_asd, user_segment_market]
  new_buyers:
    - [vertical, logical_category, region, city, is_asd, user_segment_market]
  items_closed_by_user:
    - [vertical, logical_category, region, city, is_asd, user_segment_market]
  new_listers:
    - [vertical, logical_category, region, city, is_asd, user_segment_market]
  credit_cash_revenue_issue_dt:
    - [vertical]
  buyer_delivery_orders_paid:
    - [vertical, logical_category, region, city, category, subcategory]


by_metric_list:
  app_errors: [[app_version]]
  transport_m42: [[category, subcategory, param1, is_asd, condition],[vertical, logical_category, logical_param1, is_asd, condition]]
  classified_revenue: [[vertical, logical_category, region, is_asd, user_segment_market, condition]]

  cube__is_logged_in__region__vertical: [[is_logged_in, region, vertical]]
  cube__logical_category__region__vertical: [[logical_category, region, vertical]]
  cube__city__logical_category__region__vertical: [[city, logical_category, region, vertical]]
  cube__is_logged_in__logical_category__region__vertical: [[is_logged_in, logical_category, region, vertical]]
  cube__city__is_asd__logical_category__region__user_segment_market__vertical: [[city, is_asd, logical_category, region, user_segment_market, vertical]]
  cube__is_asd__is_logged_in__logical_category__region__user_segment_market__vertical: [[is_asd, is_logged_in, logical_category, region, user_segment_market, vertical]]
  cube__city__is_asd__logical_category__platform__region__user_segment_market__vertical: [[city, is_asd, logical_category, platform, region, user_segment_market, vertical]]
  cube__category__city__is_asd__param1__platform__region__subcategory__user_segment_market: [[category, city, is_asd, param1, platform, region, subcategory, user_segment_market]]
